src/app.py
from flask import Flask, render_template
from routes.routes import turno_route

# Intancia de la app
app = Flask(__name__)

@app.route('/')
def home():
    return render_template('index.html')

@app.errorhandler(404)
def not_found(e):
    return render_template('404.html')

app.register_blueprint(turno_route)

if __name__ == '__main__':
    app.run(debug=True)

src/routes/routes.py
from flask import Blueprint, render_template
from model.model_juego import get_juegos
from model.model_producto import creaListaProductos

turno_route = Blueprint('tuturno', __name__, url_prefix='/tuturno')

@turno_route.route('/menu/<elemento>', methods = ['POST', 'GET'])
def menu(elemento):

    if str(elemento) == 'bebestible':
        myquery = { "tipo_producto" : "Bebestible" }
        productos = creaListaProductos(myquery)
        return render_template('menu.html', cafeteria = productos)
    
    elif str(elemento) == 'pasteleria':
        myquery = { "tipo_producto" : "Pasteleria" }
        productos = creaListaProductos(myquery)
        return render_template('menu.html', cafeteria = productos)
    
    else:
        myquery = { "tipo_producto" : "Cafeteria" }
        productos = creaListaProductos(myquery)

    pagina = 'menu'
    return render_template('menu.html', cafeteria = productos, pagina = pagina)

@turno_route.route('/menu')
def menu2():
    return menu('cafeteria')

@turno_route.route('/ludoteca')
def ludoteca():
    juegos = get_juegos()
    pagina = 'ludoteca'
    return render_template('ludoteca.html', juegos = juegos, pagina = pagina)

@turno_route.route('/ubicacion')
def ubicacion():
    pagina = 'ubicacion'
    return render_template('ubicacion.html', pagina = pagina)

src/templates/index.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container py-4">

        <div class="p-2 mb-2">
            {% include "slide.html" %}
        </div>
        
        <div class="p-5 mb-2 bg-body-tertiary rounded-3 border opacity-75 shadow-lg ">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold">Actividades Semanales</h1>
                <p class="col-md-8 fs-4 text-black bg-white">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum libero
                    dolorem laborum dolores, sint ducimus? Id excepturi aliquam voluptatibus et, velit, totam
                    maiores voluptatem iure quod earum, atque accusamus magni.</p>
            </div>
        </div>

        <div class="row align-items-md-stretch p-4">
            <div class="col-md-6">
                <div class="h-100 p-5 text-bg-dark rounded-3 shadow-lg">
                    <h2>Café de Especialidad</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam distinctio repellat inventore
                        quae at harum vitae error tempora qui hic quis adipisci labore ipsam similique cumque unde,
                        perferendis accusantium? Eveniet!</p>
                </div>
            </div>

            <div class="col-md-6">
                <div class="h-100 p-5 bg-body-tertiary border rounded-3 shadow-lg">
                    <h2>Visita nuestra Ludoteca</h2>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam est harum asperiores obcaecati
                        neque provident dignissimos quaerat modi, earum, ad commodi sint deserunt reiciendis
                        ratione. Eligendi recusandae consequuntur impedit esse?</p>
                    <a href="{{ url_for('tuturno.ludoteca') }}">
                        <button class="btn btn-outline-secondary" type="button">Ludoteca</button>
                    </a>
                </div>
            </div>
        </div>

        <div class="p-5 mb-4 bg-body-tertiary rounded-3 border opacity-75 shadow-lg ">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold">Horarios</h1>
                <p class="col-md-8 fs-4 text-black bg-white">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum libero
                    dolorem laborum dolores, sint ducimus? Id excepturi aliquam voluptatibus et, velit, totam
                    maiores voluptatem iure quod earum, atque accusamus magni.</p>
            </div>
        </div>

        <div class="p-5 mb-4 bg-body-tertiary rounded-3 border opacity-75 shadow-lg ">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold">Ubicación</h1>
                <p class="col-md-8 fs-4 text-black bg-white">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum libero
                    dolorem laborum dolores, sint ducimus? Id excepturi aliquam voluptatibus et, velit, totam
                    maiores voluptatem iure quod earum, atque accusamus magni.</p>
                <a href="{{ url_for('tuturno.ubicacion') }}">
                    <button class="btn btn-primary btn-lg" type="button">Ubicación</button>
                </a>
            </div>
        </div>

{% endblock %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename= 'css/main.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename= 'css/main.css')}}">
    <title>Cafetería Tu Turno</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar_color ">
        <div class="container-fluid">


            <a href="{{ url_for('home') }}">
                <img class="logo" 
                    src="{% if pagina == 'menu' %}
                        {{ url_for('static', filename='logo/LOTOTIPO TU TURNO_Mesa de trabajo 1 copia 3.png')}}
                    {% elif pagina == 'ludoteca' %} 
                        {{ url_for('static', filename='logo/LOTOTIPO TU TURNO_Mesa de trabajo 1 copia 2.png')}}
                    {% elif pagina == 'ubicacion' %}
                        {{ url_for('static', filename='logo/LOTOTIPO TU TURNO_Mesa de trabajo 1.png')}}
                    {% else %}
                        {{ url_for('static', filename='logo/LOTOTIPO TU TURNO_Mesa de trabajo 1 copia 4.png')}}
                    {% endif %}" height="100p" width="100p">
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if pagina == 'menu' %} active {% endif %}" aria-current="page"
                            href="{{ url_for('tuturno.menu', elemento='cafeteria') }}">Menú</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if pagina == 'ludoteca' %} active {% endif %}" aria-current="page"
                            href="{{ url_for('tuturno.ludoteca') }}">Ludoteca</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if pagina == 'ubicacion' %} active {% endif %}" aria-current="page"
                            href="{{ url_for('tuturno.ubicacion') }}">Ubicación</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container text-center">
        <img class="imagen-pricipal" 
        src="{% if pagina == 'menu' %}
                {{ url_for('static', filename='logo/Naranja.png')}}
            {% elif pagina == 'ludoteca' %} 
                {{ url_for('static', filename='logo/Negro.png')}}
            {% elif pagina == 'ubicacion' %}
                {{ url_for('static', filename='logo/Plomo.png')}}
            {% else %}
                {{ url_for('static', filename='logo/Lila2.png')}}
            {% endif %}">
    </div>

    <main>
        
    {% block content %}

    {% endblock %}

    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-body-secondary">&copy; Cafetería Tu Turno</p>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="{{ url_for('tuturno.menu', elemento='cafeteria') }}"
                    class="nav-link px-2 text-body-secondary">Menú</a></li>
            <li class="nav-item"><a href="{{ url_for('tuturno.ludoteca') }}"
                    class="nav-link px-2 text-body-secondary">Ludoteca</a></li>
            <li class="nav-item"><a href="{{ url_for('tuturno.ubicacion') }}"
                    class="nav-link px-2 text-body-secondary">Ubicación</a>
            </li>
            <li class="nav-item"><a href="https://www.instagram.com/tuturno.cl/?hl=es"
                    class="nav-link px-2 text-body-secondary" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-instagram" viewBox="0 0 16 16">
                        <path
                            d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334" />
                    </svg>
                </a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-tiktok" viewBox="0 0 16 16">
                        <path
                            d="M9 0h1.98c.144.715.54 1.617 1.235 2.512C12.895 3.389 13.797 4 15 4v2c-1.753 0-3.07-.814-4-1.829V11a5 5 0 1 1-5-5v2a3 3 0 1 0 3 3z" />
                    </svg>
                </a>
            </li>
        </ul>
    </footer>
</div>
</main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

src/templates/ludoteca.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">
        <div class="container py-4 text-center">
            <table id="itemsTable" class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col"><p>#</p></th>
                        <th scope="col" ><p>Nombre</p></th>
                        <th scope="col" ><p>Cantidad Jugadores</p></th>
                        <th scope="col" ><p>Edad Recomendada</p></th>
                    </tr>
                </thead>
                <tbody>
                    {% set count = namespace(c = 0) %}
                    {% for juego in juegos %}
                    {% set count.c = count.c + 1 %}
                    <tr>
                        <th scope="row"><p>{{count.c}}</p></th>
                        <td><p class="user-select-none">{{juego.nombre_juego}}</p></td>
                        <td><p class="user-select-none">{{juego.jugadores_juego}}</p></td>
                        <td><p class="user-select-none">{{juego.edad_juego}}</p></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

{% endblock %}

src/templates/menu.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">

        <div class="container  mx-auto">

            <div class="container g-4 p-4">
                <form method="POST" id="formulario">
                    <button class="btn btn_input_pri btn-lg" type="submit" form="formulario"
                        formaction="{{ url_for('tuturno.menu', elemento='cafeteria') }}">Cafeteria</button>
                    <button class="btn btn_input_sec btn-lg" type="submit" form="formulario"
                        formaction="{{ url_for('tuturno.menu', elemento='pasteleria') }}">Pasteleria</button>
                    <button class="btn btn_input_third btn-lg" type="submit" form="formulario"
                        formaction="{{ url_for('tuturno.menu', elemento='bebestible') }}">Bebestible</button>
                </form>
            </div>
            
            <div class="row row-cols-1 row-cols-md-3 g-4 p-4">
                {% for producto in cafeteria %}
                <div class="col">

                    <div class="card ">
                        <img src="{{ url_for('static', filename = 'img/productos/' + producto.foto_producto )}}"
                            class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{producto.nombre_producto}}</h5>
                            <p class="card-text">$ {{producto.valor_producto}}</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-body-secondary">{{producto.descripcion_producto}}</small>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

{% endblock %}

src/templates/slide.html
<div class="container text-center">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{{url_for('static', filename= 'img/slide/catan.jpg')}}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{{url_for('static', filename= 'img/slide/juego1.jpeg')}}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{{url_for('static', filename= 'img/slide/monopoly.jpeg')}}" class="d-block w-100" alt="...">
            </div>
        </div>
    </div>
</div>

src/templates/ubicacion.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">

        <div class="container py-4 text-center">
            <div class="map-responsive">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3328.7830827610105!2d-70.70264242516453!3d-33.45495749774163!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662c489c1368657%3A0x5021c9e5f9f86047!2sConde%20del%20Maule%204630%2C%209170413%20Estaci%C3%B3n%20Central%2C%20Regi%C3%B3n%20Metropolitana!5e0!3m2!1ses-419!2scl!4v1731972639731!5m2!1ses-419!2scl"
                    width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>

{% endblock %}